all:
	gcc -Iinclude/ src/c_app.c src/c_camera.c src/c_main.c src/c_scene.c src/c_texture.c src/c_utils.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lobj -lopengl32 -lm -o cube.exe -Wall -Wextra -Wpedantic

